ALTER TABLE public.mailbox_connections DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.emails DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_base DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.historical_emails DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.voice_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_keys DISABLE ROW LEVEL SECURITY;
